# This is a basic workflow to help you get started with Actions

name: pre-release

on:
  push:
    branches: [ master ]

jobs:
  pre-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build project
      run: |
        tar -czvf hcloud-fip-sync.tar.gz hcloud-fip-sync

    - name: Create a Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: latest
        release_name: Development Build

    - name: Upload Installer
      id: upload-release-asset-installer
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: install.sh
        asset_name: install.sh
        asset_content_type: application/x-sh

    - name: Upload Files
      id: upload-release-asset-files
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: hcloud-fip-sync.tar.gz
        asset_name: hcloud-fip-sync.tar.gz
        asset_content_type: application/tar+gzip
